### ISSUE TITLE
Consider setting list.activeSelectionBackground and other workbench colors

### ISSUE THREAD

**Issue by amiroff** [AhmedAbdulrahman/aylin-vscode-theme#2]
Hello! Thanks for another great update!

One problem though, active selections in lists do not have highlights. I had to use the following customization to fix it and while at it, added a more visible border to panels and status bar hovers.

```json
"workbench.colorCustomizations": {
    "list.activeSelectionBackground": "#27395754",
    "panel.border": "#27395754",
    "statusBarItem.hoverBackground": "#27395754"
  },
```

Maybe you'll consider these ideas.

**Comment by AhmedAbdulrahman** [comment]
@amiroff Hi Metin,

Thanks a lot thats a nice catch :) sure thing I updated it with your suggestion with a bit of tweaking other things like: `quickInput`, `notification` and `editorGroup.emptyBackground` for empty window :) 

![Screen Shot 2020-12-23 at 15 06 36](https://user-images.githubusercontent.com/10485129/103003425-12705d80-4531-11eb-8ad1-bf991cdcde25.png)

![Screen Shot 2020-12-23 at 15 11 08](https://user-images.githubusercontent.com/10485129/103003463-1ef4b600-4531-11eb-8350-abcaf9ac0062.png)

**Comment by amiroff** [comment]
Looks awesome! Cannot wait to get this update! Well done!

**Comment by AhmedAbdulrahman** [comment]
@amiroff Published ;)
